### PR TITLE
chore(dist): Removed dist/ from git index

### PR DESCRIPTION
**Pull request by SomeKittens**
Build files should not be in the index.  This will avoid massive diffs in future PRs

### CODE REVIEW

**Comment by kentcdodds** [comment]
There are many different opinions on this. I'm in the "keep `dist` in source control" camp. The main reasons I think this is valuable:

1. Easier for people to find the distribution file - there are a lot of reasons this is useful
2. Less complex releases

I don't have a problem including the `dist` as long as we make commits to it as simple as: `'Release 1.3.1'`

I've done this with several of my libraries and it's never been a problem from me.

**Comment by SomeKittens** [comment]
The trouble I was running into is that `dist/hint.js` is auto-generated by gulp, so anytime I make changes to a watched file, we get a identical changes in dist.

`dist/hint.js` is also tracking all of our `require`'d files, so that could cause problems in the future if things get out of sync.  (i.e. issues being opened because a bug that was fixed in a patch version of `angular-hint` was not reflected in latest dist).  It almost becomes the poor man's shrinkwrap.

None of these are insurmountable - thoughts?

**Comment by kentcdodds** [comment]
I may be misunderstanding, but as long as you don't actually commit the changes until a release comes up then you should be fine, right?

**Comment by SomeKittens** [comment]
That could work, but the changes will still be in `git status` and `git diff`.

**Comment by SomeKittens** [comment]
Some additional thoughts:
 - We don't check in `node_modules` and binaries, so why a compiled file?
 - This was helpful in me reasoning around the code

At this point, I'm in favor of keeping dist around until we have clear and up-to-date instructions on running the build (i.e. anyone can generate a dist and it'll always be the same).

**Pull request closed without merging**
